//==============================================================================
// Generated by language_helper_generator
//==============================================================================

const enLanguageData = <String, String>{
  // TODO: Translate text
  "Hello, world! 1": "Hello, world! 1",
  // TODO: Translate text
  "This is a \"quoted\" string 1": "This is a \"quoted\" string 1",
  // TODO: Translate text
  "This is a 'quoted' string 1": "This is a 'quoted' string 1",
  // TODO: Translate text
  "This is a string with @{num} parameters 1":
      "This is a string with @{num} parameters 1",
  // TODO: Translate text
  "Hello, wsa fa;senf jb awbdfb hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "Hello, wsa fa;senf jb awbdfb hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1",
  // TODO: Translate text
  "Hello, wsa fa;senf jb awbdfrr b hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "Hello, wsa fa;senf jb awbdfrr b hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1",
  // TODO: Translate text
  "This is a 'quoted' string 2": "This is a 'quoted' string 2",
  // TODO: Translate text
  "This is a string with @{num} parameters 2":
      "This is a string with @{num} parameters 2",
  // TODO: Translate text
  "Hello, world! 2": "Hello, world! 2",
  // TODO: Translate text
  "This is a \"quoted\" string 2": "This is a \"quoted\" string 2",
  // TODO: Translate text
  "This is a 'quoted' string 3": "This is a 'quoted' string 3",
  // TODO: Translate text
  "This is a string with @{num} parameters 3":
      "This is a string with @{num} parameters 3",
  // TODO: Translate text
  "This is the same text": "This is the same text",
  // TODO: Translate text
  "        This is the same text\n        ":
      "        This is the same text\n        ",
  // TODO: Translate text
  "This is a\n          multi-lines text\n          ":
      "This is a\n          multi-lines text\n          ",
  // TODO: Translate text
  "Hello, world! 3": "Hello, world! 3",
  // TODO: Translate text
  "This is a \"quoted\" string 3": "This is a \"quoted\" string 3",
  // TODO: Translate text
  "This is a 'quoted' string 4": "This is a 'quoted' string 4",
  // TODO: Translate text
  "This is a string with @{num} parameters 4":
      "This is a string with @{num} parameters 4",
  // TODO: Translate text
  "This is a \"quoted\" string 5": "This is a \"quoted\" string 5",
  // TODO: Translate text
  "This is a 'quoted' string 5": "This is a 'quoted' string 5",
};
