//==============================================================================
// Generated Date: 2025-10-23T17:38:55.775060
//
// Generated By language_helper - You can freely edit this file
//==============================================================================

// ignore_for_file: prefer_single_quotes

const enLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: page_1/page_1.dart
  ///===========================================================================
  "@path_page_1/page_1.dart": "",
  // TODO: Translate this text to en language
  "Hello, world! 1": "",
  // TODO: Translate this text to en language
  "This is a \"quoted\" string 1": "",
  // TODO: Translate this text to en language
  "This is a 'quoted' string 1": "",
  // TODO: Translate this text to en language
  "This is a string with @{num} parameters 1": "",
  // TODO: Translate this text to en language
  "Hello, wsa fa;senf jb awbdfb hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "",
  // TODO: Translate this text to en language
  "Hello, wsa fa;senf jb awbdfrr b hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "",

  ///===========================================================================
  /// Path: page_1/page_2.dart
  ///===========================================================================
  "@path_page_1/page_2.dart": "",
  // TODO: Translate this text to en language
  "This is a 'quoted' string 2": "",
  // TODO: Translate this text to en language
  "This is a string with @{num} parameters 2": "",

  ///===========================================================================
  /// Path: page_2/page_1.dart
  ///===========================================================================
  "@path_page_2/page_1.dart": "",
  // TODO: Translate this text to en language
  "Hello, world! 2": "",
  // TODO: Translate this text to en language
  "This is a \"quoted\" string 2": "",
  // TODO: Translate this text to en language
  "This is a 'quoted' string 3": "",
  // TODO: Translate this text to en language
  "This is a string with @{num} parameters 3": "",

  ///===========================================================================
  /// Path: page_2/page_3.dart
  ///===========================================================================
  "@path_page_2/page_3.dart": "",
  // TODO: Translate this text to en language
  "This is the same text": "",
  // TODO: Translate this text to en language
  "        This is the same text\n        ": "",
  // TODO: Translate this text to en language
  "This is a\n          multi-lines text\n          ": "",

  ///===========================================================================
  /// Path: page_2/page_2.dart
  ///===========================================================================
  "@path_page_2/page_2.dart": "",
  // TODO: Translate this text to en language
  "Hello, world! 3": "",
  // TODO: Translate this text to en language
  "This is a \"quoted\" string 3": "",
  // TODO: Translate this text to en language
  "This is a 'quoted' string 4": "",
  // TODO: Translate this text to en language
  "This is a string with @{num} parameters 4": "",
  // TODO: Translate this text to en language
  "This is a \"quoted\" string 5": "",
  // TODO: Translate this text to en language
  "This is a 'quoted' string 5": "",
};
