//==============================================================================
// Generated Date: 2025-10-24T15:10:41.585411
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes

const viLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: page_1/page_1.dart
  ///===========================================================================
  "@path_page_1/page_1.dart": "",
  // TODO: Add `vi` language translation
  "Hello, world! 1": "Hello, world! 1",
  // TODO: Add `vi` language translation
  "This is a \"quoted\" string 1": "This is a \"quoted\" string 1",
  // TODO: Add `vi` language translation
  "This is a 'quoted' string 1": "This is a 'quoted' string 1",
  // TODO: Add `vi` language translation
  "This is a string with @{num} parameters 1":
      "This is a string with @{num} parameters 1",
  // TODO: Add `vi` language translation
  "Hello, wsa fa;senf jb awbdfb hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "Hello, wsa fa;senf jb awbdfb hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1",
  // TODO: Add `vi` language translation
  "Hello, wsa fa;senf jb awbdfrr b hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "Hello, wsa fa;senf jb awbdfrr b hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1",

  ///===========================================================================
  /// Path: page_1/page_2.dart
  ///===========================================================================
  "@path_page_1/page_2.dart": "",
  // TODO: Add `vi` language translation
  "This is a 'quoted' string 2": "This is a 'quoted' string 2",
  // TODO: Add `vi` language translation
  "This is a string with @{num} parameters 2":
      "This is a string with @{num} parameters 2",

  ///===========================================================================
  /// Path: page_2/page_1.dart
  ///===========================================================================
  "@path_page_2/page_1.dart": "",
  // TODO: Add `vi` language translation
  "Hello, world! 2": "Hello, world! 2",
  // TODO: Add `vi` language translation
  "This is a \"quoted\" string 2": "This is a \"quoted\" string 2",
  // TODO: Add `vi` language translation
  "This is a 'quoted' string 3": "This is a 'quoted' string 3",
  // TODO: Add `vi` language translation
  "This is a string with @{num} parameters 3":
      "This is a string with @{num} parameters 3",

  ///===========================================================================
  /// Path: page_2/page_3.dart
  ///===========================================================================
  "@path_page_2/page_3.dart": "",
  // TODO: Add `vi` language translation
  "This is the same text": "This is the same text",
  // TODO: Add `vi` language translation
  "        This is the same text\n        ":
      "        This is the same text\n        ",
  // TODO: Add `vi` language translation
  "This is a\n          multi-lines text\n          ":
      "This is a\n          multi-lines text\n          ",

  ///===========================================================================
  /// Path: page_2/page_2.dart
  ///===========================================================================
  "@path_page_2/page_2.dart": "",
  // TODO: Add `vi` language translation
  "Hello, world! 3": "Hello, world! 3",
  // TODO: Add `vi` language translation
  "This is a \"quoted\" string 3": "This is a \"quoted\" string 3",
  // TODO: Add `vi` language translation
  "This is a 'quoted' string 4": "This is a 'quoted' string 4",
  // TODO: Add `vi` language translation
  "This is a string with @{num} parameters 4":
      "This is a string with @{num} parameters 4",
  // TODO: Add `vi` language translation
  "This is a \"quoted\" string 5": "This is a \"quoted\" string 5",
  // TODO: Add `vi` language translation
  "This is a 'quoted' string 5": "This is a 'quoted' string 5",
};
