//==============================================================================
// Generated Date: 2025-10-24T10:28:31.315778
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// ignore_for_file: prefer_single_quotes

const zhLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: page_1/page_1.dart
  ///===========================================================================
  "@path_page_1/page_1.dart": "",
  // TODO: Add `zh` language translation
  "Hello, world! 1": "",
  // TODO: Add `zh` language translation
  "This is a \"quoted\" string 1": "",
  // TODO: Add `zh` language translation
  "This is a 'quoted' string 1": "",
  // TODO: Add `zh` language translation
  "This is a string with @{num} parameters 1": "",
  // TODO: Add `zh` language translation
  "Hello, wsa fa;senf jb awbdfb hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "",
  // TODO: Add `zh` language translation
  "Hello, wsa fa;senf jb awbdfrr b hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "",

  ///===========================================================================
  /// Path: page_1/page_2.dart
  ///===========================================================================
  "@path_page_1/page_2.dart": "",
  // TODO: Add `zh` language translation
  "This is a 'quoted' string 2": "",
  // TODO: Add `zh` language translation
  "This is a string with @{num} parameters 2": "",

  ///===========================================================================
  /// Path: page_2/page_1.dart
  ///===========================================================================
  "@path_page_2/page_1.dart": "",
  // TODO: Add `zh` language translation
  "Hello, world! 2": "",
  // TODO: Add `zh` language translation
  "This is a \"quoted\" string 2": "",
  // TODO: Add `zh` language translation
  "This is a 'quoted' string 3": "",
  // TODO: Add `zh` language translation
  "This is a string with @{num} parameters 3": "",

  ///===========================================================================
  /// Path: page_2/page_3.dart
  ///===========================================================================
  "@path_page_2/page_3.dart": "",
  // TODO: Add `zh` language translation
  "This is the same text": "",
  // TODO: Add `zh` language translation
  "        This is the same text\n        ": "",
  // TODO: Add `zh` language translation
  "This is a\n          multi-lines text\n          ": "",

  ///===========================================================================
  /// Path: page_2/page_2.dart
  ///===========================================================================
  "@path_page_2/page_2.dart": "",
  // TODO: Add `zh` language translation
  "Hello, world! 3": "",
  // TODO: Add `zh` language translation
  "This is a \"quoted\" string 3": "",
  // TODO: Add `zh` language translation
  "This is a 'quoted' string 4": "",
  // TODO: Add `zh` language translation
  "This is a string with @{num} parameters 4": "",
  // TODO: Add `zh` language translation
  "This is a \"quoted\" string 5": "",
  // TODO: Add `zh` language translation
  "This is a 'quoted' string 5": "",
};
