//==============================================================================
// Generated Date: 2023-12-30T23:05:37.889688
//
// Code Generated By language_helper - Do Not Modify By Hand
//==============================================================================

// ignore_for_file: prefer_single_quotes

part of 'language_data.dart';

const analysisLanguageData = {
  ///===========================================================================
  /// Path: ./lib/page_1/page_1.dart
  ///===========================================================================
  "Hello, world! 1": "Hello, world! 1",
  'This is a "quoted" string 1': 'This is a "quoted" string 1',
  "This is a 'quoted' string 1": "This is a 'quoted' string 1",
  'This is a string with @{num} parameters 1':
      'This is a string with @{num} parameters 1',
  "Hello, wsa fa;senf jb awbdfb hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1":
      "Hello, wsa fa;senf jb awbdfb hkbkahbfwlbljbwa bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1",
  'Hello, wsa fa;senf jb awbdfrr b hkbkahbfwlbljbwa '
          'bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1':
      'Hello, wsa fa;senf jb awbdfrr b hkbkahbfwlbljbwa '
          'bjfbenqbfolaejbcfoj oljbnjafjlbqorld! 1',
  // 'This text contains variable $text7': 'This text contains variable $text7',  // Contains variable

  ///===========================================================================
  /// Path: ./lib/page_1/page_2.dart
  ///===========================================================================
  // "Hello, world! 1": "Hello, world! 1",  // Duplicated
  // 'This is a "quoted" string 1': 'This is a "quoted" string 1',  // Duplicated
  "This is a 'quoted' string 2": "This is a 'quoted' string 2",
  'This is a string with @{num} parameters 2':
      'This is a string with @{num} parameters 2',

  ///===========================================================================
  /// Path: ./lib/page_2/page_1.dart
  ///===========================================================================
  "Hello, world! 2": "Hello, world! 2",
  'This is a "quoted" string 2': 'This is a "quoted" string 2',
  "This is a 'quoted' string 3": "This is a 'quoted' string 3",
  'This is a string with @{num} parameters 3':
      'This is a string with @{num} parameters 3',

  ///===========================================================================
  /// Path: ./lib/page_2/page_3.dart
  ///===========================================================================
  r"""This is the same text""": r"""This is the same text""",
  """
        This is the same text
        """: """
        This is the same text
        """,
  // """This is a $variable text""": """This is a $variable text""",  // Contains variable
  r"""This is a
          multi-lines text
          """: r"""This is a
          multi-lines text
          """,

  ///===========================================================================
  /// Path: ./lib/page_2/page_2.dart
  ///===========================================================================
  "Hello, world! 3": "Hello, world! 3",
  'This is a "quoted" string 3': 'This is a "quoted" string 3',
  "This is a 'quoted' string 4": "This is a 'quoted' string 4",
  'This is a string with @{num} parameters 4':
      'This is a string with @{num} parameters 4',
  'This is a "quoted" string 5': 'This is a "quoted" string 5',
  // 'This is a "quoted" string 5': 'This is a "quoted" string 5',  // Duplicated
  "This is a 'quoted' string 5": "This is a 'quoted' string 5",
  // "This is a 'quoted' string 5": "This is a 'quoted' string 5",  // Duplicated
};
