//==============================================================================
// Generated Date: 2025-10-27T11:18:04.545503
//
// Generated by language_helper. Please do not modify by hand
//==============================================================================

// Keeps format for the parser
// ignore_for_file: always_use_package_imports

import 'package:language_helper/language_helper.dart';

import 'data/en.dart';
import 'data/vi.dart';

final LazyLanguageData languageData = {
  LanguageCodes.en: () => enLanguageData,
  LanguageCodes.vi: () => viLanguageData,
};
