name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Dart Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
        
    - name: Install dependencies
      run: dart pub get
      
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Analyze project source
      run: dart analyze --fatal-infos
      
    - name: Run tests
      run: dart test --coverage=coverage
      
    - name: Generate coverage report
      run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib --check-ignore

    - name: Convert to relative paths
      if: runner.os == 'Linux' || runner.os == 'Windows'
      run: sed -i 's|SF:.*/lib|SF:lib|' coverage/lcov.info
    
    - name: Convert to relative paths (macOS)
      if: runner.os == 'macOS'
      run: sed -i '' 's|SF:.*/lib|SF:lib|' coverage/lcov.info

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: lamnhan066/isolate_manager_generator
